### ISSUE TITLE
Y24-232 - [BUG] As a CASM Project Mgr (LH) I believe sequencing information should be shown in the Sample Tracking report when pre-made libraries are submitted to SeqOps.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sample-tracking#21]
There seems to be a problem with submissions of pre-made libraries – in CASM, this is mostly our CRISPR library submissions – these undergo library QC before being loaded on the sequencers, but when we have checked a few different CRISPR studies, there is no sequencing information recorded. i.e. we would expect dilution and library steps to be null, but we would expect there to be sequencing values. Example projects are 6268 and 5621.

I suspect that either the mlwh events the query is looking for are not being created OR the sequencing runs are not linking back to the original submission plate in the same way "normal" samples do.

**Comment by khelwood** [comment]
These are rows that *are* in the report, but some information is missing from the rows.

**Comment by khelwood** [comment]
@TWJW-SANGER  The view joins the `sample_flowcell_view` to events using the subject uuid. There are no sequencing events in the events schema for those uuids. There are only `sample_manifest.updated`, `labware.received` and `order_made` events.

**Comment by TWJW-SANGER** [comment]
@khelwood That does seem odd.

Looking at the study 6268 in SequenceScape I can see a lot more plates/sample than in the report.

For example in the relative url /studies/6268/information?page=28&per_page=50&summary=sample-progress

I can see a sample 6268STDY14727156 that comes from a stock plate SQPP-51362-G, which doesn't appear in the report.
But checking events in mlwh_events I do find a number of sequencing complete events:

| 4682791 | sequencing_complete   | 6268STDY14727156 | 2024-07-30 21:01:00 | lane=SQPP51362 A1:D5,library_source_labware=SQPP-51362-G,project=OTAR2-062 Effective Combination Therapies in Tumours,sequencing_source_labware=NT1839228N,stock_plate=SQPP-51362-G,study=ENCORE: New Targets for Effective Combination Therapies in Tumors with Unmet Medical Need                                                                  | pipeline=NovaSeqX PE,read_length=100,result=passed,team=Illumina-HTP


There might be multiple problems here. Could you double check why the above plate / sample isn't showing up in the report?

Thanks.

**Comment by khelwood** [comment]
@TWJW-SANGER The barcode `SQPP-51362-G` doesn't appear in the mlwarehouse `stock_resource` table. I can see it does exist in SS and seem to belong to a stock plate, so I'm not sure what distinction keeps it out of the warehouse.

**Comment by khelwood** [comment]
This seems to be impossible with the current contents of the warehouse. `stock_resource` is the table that tells you which samples are in which labware (and rows are aggregated by labware). Events reference multiple labware and multiple samples, so they can't be used to link labware and samples.
